server:
  port: 8080

#eureka:         #tells about the Eureka server details and its refresh time
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://service-registry:8080/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

logging:
  level:
    com.example.store: DEBUG

ribbon:
  ReadTimeout: 5000

#opentracing:
#  jaeger:
#    udp-sender:
#      host: jaeger-agent
#      port: 6831

opentracing:
  jaeger:
    enable-b3-propagation: true
    http-sender:
      url: ${JAEGER_COLLECTOR_ENDPOINT:http://jaeger-collector.istio-system.svc:14268/api/traces}